#!/bin/sh

# Configure your favorite diff program here.
DIFF="/usr/bin/vimdiff"
for arg in $@; do
  if [ "$arg" = "-nv" ]; then
    DIFF="diff -u"
  fi
done
# Subversion provides the paths we need as the sixth and seventh
# parameters.
LEFT=${6}
RIGHT=${7}
# Call the diff command (change the following line to make sense for
# your merge program).
$DIFF $LEFT $RIGHT

